import Foundation

extension ShortcutID {
    public var title: String {
        switch self {
        case .settings: "Settings…"
        case .commandBar: "Command Center…"
        case .reload: "Reload Page"
        case .undoBrowserAction: "Undo Browser Action"
        case .toggleTabLayout: "Toggle Tab Layout"
        case .toggleSidebar: "Toggle Sidebar"
        case .newWindow: "New Window"
        case .newPrivateWindow: "New Private Window"
        case .newTab: "New Tab"
        case .newPrivateTab: "New Private Tab"
        case .closeTab: "Close Tab"
        case .reopenClosedTab: "Reopen Closed Tab"
        case .findOnPage: "Find on Page…"
        case .findNext: "Find Next"
        case .findPrevious: "Find Previous"
        case .closeFind: "Close Find on Page"
        case .fillLogin: "Fill Login"
        case .openLocation: "Open Location…"
        case .copyURL: "Copy Address"
        case .pasteAndGo: "Paste and Go"
        case .print: "Print…"
        case .toggleTabStrip: "Toggle Tab Strip"
        case .showBookmarksBar: "Toggle Bookmarks Bar"
        case .focusMode: "Focus Mode"
        case .toggleReader: "Toggle Reader"
        case .floatVideo: "Float Video"
        case .zoomIn: "Zoom In"
        case .zoomOut: "Zoom Out"
        case .zoomReset: "Actual Size"
        case .splitView: "Split View"
        case .addPane: "Add Pane"
        case .switchPane: "Switch Pane"
        case .nextTab: "Next Tab"
        case .previousTab: "Previous Tab"
        case .lastActiveTab: "Last Active Tab"
        case .selectTabRight: "Select Tab to the Right"
        case .selectTabLeft: "Select Tab to the Left"
        case .pinTab: "Pin Tab"
        case .duplicateTab: "Duplicate Tab"
        case .closeOtherTabs: "Close Other Tabs"
        case .muteTab: "Mute Tab"
        case .goBack: "Back"
        case .goForward: "Forward"
        case .hardReload: "Reload Ignoring Cache"
        case .stopLoading: "Stop Loading"
        case .goHome: "Home"
        case .showHistory: "Show All History…"
        case .bookmarkPage: "Bookmark Page"
        case .showBookmarks: "Bookmarks…"
        case .showDownloads: "Downloads…"
        case .showTimeline: "Tab Timeline…"
        case .showSitePrivacy: "Site Privacy…"
        case .toggleDevTools: "Developer Tools"
        case .toggleConsole: "JavaScript Console"
        case .showTabGroups: "Tab Groups…"
        }
    }
}
