import RedentKit

/// The menu chords that shipped before bindings existed. Tests lock this table.
enum PreviousMenuShortcuts {
    static let all: [ShortcutID: KeyChord] = [
        .settings: .command(","),
        .commandBar: .command("k"),
        .reload: .command("r"),
        .undoBrowserAction: KeyChord(key: "z", modifiers: [.command, .option]),
        .toggleTabLayout: .command("s"),
        .toggleSidebar: .command("b"),
        .newWindow: .command("n"),
        .newPrivateWindow: KeyChord(key: "n", modifiers: [.command, .shift]),
        .newTab: .command("t"),
        .newPrivateTab: KeyChord(key: "n", modifiers: [.command, .control]),
        .closeTab: .command("w"),
        .reopenClosedTab: KeyChord(key: "t", modifiers: [.command, .shift]),
        .findOnPage: .command("f"),
        .findNext: .command("g"),
        .findPrevious: KeyChord(key: "g", modifiers: [.command, .shift]),
        .closeFind: KeyChord(key: "escape", modifiers: []),
        .fillLogin: .command("\\"),
        .openLocation: .command("l"),
        .copyURL: KeyChord(key: "c", modifiers: [.command, .shift]),
        .pasteAndGo: KeyChord(key: "v", modifiers: [.command, .shift]),
        .print: .command("p"),
        .toggleTabStrip: .command("\\"),
        .showBookmarksBar: KeyChord(key: "b", modifiers: [.command, .shift]),
        .focusMode: KeyChord(key: "f", modifiers: [.command, .shift]),
        .toggleReader: KeyChord(key: "r", modifiers: [.command, .control]),
        .floatVideo: KeyChord(key: "v", modifiers: [.command, .control]),
        .zoomIn: .command("+"),
        .zoomOut: .command("-"),
        .zoomReset: .command("0"),
        .splitView: KeyChord(key: "d", modifiers: [.command, .shift]),
        .addPane: KeyChord(key: "d", modifiers: [.command, .option]),
        .switchPane: KeyChord(key: "]", modifiers: [.command, .option]),
        .nextTab: .command("j"),
        .previousTab: KeyChord(key: "tab", modifiers: [.control, .shift]),
        .lastActiveTab: KeyChord(key: "tab", modifiers: .control),
        .selectTabRight: KeyChord(key: "]", modifiers: [.command, .shift]),
        .selectTabLeft: KeyChord(key: "[", modifiers: [.command, .shift]),
        .pinTab: KeyChord(key: "p", modifiers: [.command, .shift]),
        .closeOtherTabs: KeyChord(key: "w", modifiers: [.command, .option]),
        .muteTab: KeyChord(key: "m", modifiers: .control),
        .goBack: .command("["),
        .goForward: .command("]"),
        .hardReload: KeyChord(key: "r", modifiers: [.command, .shift]),
        .stopLoading: .command("."),
        .goHome: KeyChord(key: "h", modifiers: [.command, .shift]),
        .showHistory: .command("y"),
        .bookmarkPage: .command("d"),
        .showBookmarks: KeyChord(key: "b", modifiers: [.command, .option]),
        .showDownloads: KeyChord(key: "j", modifiers: [.command, .shift]),
        .showTimeline: KeyChord(key: "y", modifiers: [.command, .shift]),
        .showSitePrivacy: KeyChord(key: "i", modifiers: [.command, .shift]),
        .toggleDevTools: KeyChord(key: "i", modifiers: [.command, .option]),
        .toggleConsole: KeyChord(key: "j", modifiers: [.command, .option]),
        .showTabGroups: KeyChord(key: "g", modifiers: [.control, .option])
    ]
}
