var H=Object.defineProperty;var O=(o,e)=>{for(var s in e)H(o,s,{get:e[s],enumerable:!0})};var y={};O(y,{WarningErrorCounter:()=>w,WarningErrorCounterWidget:()=>p});import"./../../ui/components/icon_button/icon_button.js";import*as u from"./../../core/common/common.js";import*as h from"./../../core/host/host.js";import*as T from"./../../core/i18n/i18n.js";import*as t from"./../../core/sdk/sdk.js";import*as m from"./../../models/issues_manager/issues_manager.js";import*as D from"./../../ui/components/issue_counter/issue_counter.js";import*as a from"./../../ui/legacy/legacy.js";import*as x from"./../../ui/lit/lit.js";import*as C from"./../../ui/visual_logging/visual_logging.js";var{html:M,nothing:V,render:N}=x,c={sErrors:"{n, plural, =1 {# error} other {# errors}}",sWarnings:"{n, plural, =1 {# warning} other {# warnings}}",openConsoleToViewS:"Open Console to view {PH1}",openIssuesToView:"{n, plural, =1 {Open Issues to view # issue:} other {Open Issues to view # issues:}}"},k=T.i18n.registerUIStrings("panels/console_counters/WarningErrorCounter.ts",c),g=T.i18n.getLocalizedString.bind(void 0,k),W=(o,e,s)=>{let n=m.IssuesManager.IssuesManager.instance(),r=U=>U===0?void 0:`${U}`,{errors:i,warnings:l,issues:S,compact:b}=o,f=g(c.sErrors,{n:i}),v=g(c.sWarnings,{n:l}),d="";i&&l?d=`${f}, ${v}`:i?d=f:l&&(d=v);let E=g(c.openConsoleToViewS,{PH1:d}),$={clickHandler:u.Console.Console.instance().show.bind(u.Console.Console.instance()),accessibleName:E,compact:b,groups:[{iconName:"cross-circle-filled",text:r(i)},{iconName:"warning-filled",text:r(l)}]},K=D.IssueCounter.getIssueCountsEnumeration(n),L=`${g(c.openIssuesToView,{n:S})} ${K}`,F={clickHandler:o.showIssuesHandler,issuesManager:n,compact:b,accessibleName:L,displayMode:"OnlyMostImportant"};N(M`<div class="status-buttons"
         >${i+l?M`<icon-button
            .data=${$}
            title=${E}
            class=${"small"}
            jslog=${C.counter("console").track({click:!0})}
         ></icon-button>`:V}${S?M`<devtools-issue-counter
            class=${"main-toolbar"}
            title=${L}
            .data=${F}
            jslog=${C.counter("issue").track({click:!0})}
         ></devtools-issue-counter>`:V}</div>`,s)},p=class o extends a.Widget.Widget{setVisibility;view;throttler;updatingForTest;compact;static instanceForTest=null;constructor(e,s,n=W){super(e),this.setVisibility=s,this.view=n,this.throttler=new u.Throttler.Throttler(100),t.TargetManager.TargetManager.instance().addModelListener(t.ConsoleModel.ConsoleModel,t.ConsoleModel.Events.ConsoleCleared,this.update,this),t.TargetManager.TargetManager.instance().addModelListener(t.ConsoleModel.ConsoleModel,t.ConsoleModel.Events.MessageAdded,this.update,this),t.TargetManager.TargetManager.instance().addModelListener(t.ConsoleModel.ConsoleModel,t.ConsoleModel.Events.MessageUpdated,this.update,this),m.IssuesManager.IssuesManager.instance().addEventListener("IssuesCountUpdated",this.update,this),this.update(),o.instanceForTest=this}onSetCompactLayout(e){this.setCompactLayout(e.data)}setCompactLayout(e){this.compact=e,this.performUpdate()}updatedForTest(){}update(){this.updatingForTest=!0,this.throttler.schedule(this.performUpdate.bind(this))}get titlesForTesting(){let e=this.contentElement.querySelector("icon-button")?.shadowRoot?.querySelector("button");return e?e.getAttribute("aria-label"):null}showIssues(){h.userMetrics.issuesPanelOpenedFrom(h.UserMetrics.IssueOpener.STATUS_BAR_ISSUES_COUNTER),a.ViewManager.ViewManager.instance().showView("issues-pane")}async performUpdate(){let e=t.ConsoleModel.ConsoleModel.allErrors(t.TargetManager.TargetManager.instance()),s=t.ConsoleModel.ConsoleModel.allWarnings(t.TargetManager.TargetManager.instance()),r=m.IssuesManager.IssuesManager.instance().numberOfIssues();this.view({compact:this.compact,errors:e,warnings:s,issues:r,showIssuesHandler:this.showIssues.bind(this)},{},this.contentElement),this.setVisibility(!!(e||s||r)),a.InspectorView.InspectorView.instance().toolbarItemResized(),this.updatingForTest=!1,this.updatedForTest()}},I,w=class o{toolbarItem;constructor(){let e=document.createElement("devtools-widget"),s=new a.Toolbar.ToolbarItemWithCompactLayout(e);s.setVisible(!1);let n=new p(e,s.setVisible.bind(s));s.addEventListener("CompactLayoutUpdated",n.onSetCompactLayout,n),this.toolbarItem=s}item(){return this.toolbarItem}static instance(e={forceNew:null}){let{forceNew:s}=e;return(!I||s)&&(I=new o),I}};export{y as WarningErrorCounter};
//# sourceMappingURL=console_counters.js.map
